# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

name: $(Build.DefinitionName)-$(date:yyyyMMdd)-$(rev:rr)

variables:
  buildConfiguration: 'Release'
  imageName: $(Build.BuildNumber)
  dockerTag: $(dockerId).azurecr.io/$(imageName)
  
pool:
    vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo "Build config: $(buildConfiguration)"
    echo "Image Name: $(imageName)"
    echo "Docker Tag: $(dockerTag)"
    ls -al
    pwd


#- script: |
#    dotnet build --configuration $(buildConfiguration)
#    dotnet publish --configuration $(buildConfiguration) --output out

- script: |
    docker build -f 'johnsommerville.com/Dockerfile.ci' -t $(dockerTag) .
    docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
    docker push $(dockerTag) .
  env:
    pswd: $(dockerPassword)
    

- script: |
    echo "Post:"
    ls -al
    pwd